/* Oracle for the Lean Adler-32 model: prints, for each pseudorandom buffer,
   a Lean `theorem` asserting that the model agrees with zlib's own adler32.
   Compile against the real zlib source so the answer is zlib's, not ours. */
#include <stdio.h>
#include <stdlib.h>
#include "zlib.h"

int main(int argc, char **argv) {
    int cases = argc > 1 ? atoi(argv[1]) : 50;
    unsigned seed = argc > 2 ? (unsigned)atoi(argv[2]) : 12345u;
    unsigned char buf[4096];
    srandom(seed);
    printf("import ZAdler32\nopen ZAdler32\nset_option maxRecDepth 100000\n\n");
    printf("-- generated by test/lean/adler_oracle.c against zlib's own adler32\n");
    for (int t = 0; t < cases; t++) {
        int n = (int)(random() % 300);
        for (int i = 0; i < n; i++) buf[i] = (unsigned char)(random() % 256);
        uLong a = adler32(1L, buf, (uInt)n);
        printf("theorem case_%d : adler32Model 1 [", t);
        for (int i = 0; i < n; i++) printf("%s%u", i ? ", " : "", buf[i]);
        printf("] = %lu := by decide\n", (unsigned long)a);
    }
    return 0;
}
