#!/usr/bin/env python3
"""Generate matched Rocq and Lean test batteries for CC.Values and CC.Memdata.

Same idea as gen_int_diff.py, one level up the stack: every result is reduced to
a single integer code so the two outputs can be diffed line by line.

  - sem_diff.v    evaluates CompCert's real common/Values.v + common/Memdata.v
  - SemDiff.lean  evaluates CCLib/Values.lean + CCLib/Memdata.lean
"""
import os

# ---------------------------------------------------------------- encoders
COQ_HDR = r"""(* GENERATED by gen_sem_diff.py -- differential test oracle *)
From compcert Require Import Integers Floats Values Memdata AST.
Require Import ZArith List.
Local Open Scope Z_scope.
Set Printing Width 200.

Definition vtag (v: val) : Z :=
  match v with
  | Vundef => 0 | Vint _ => 1 | Vlong _ => 2
  | Vfloat _ => 3 | Vsingle _ => 4 | Vptr _ _ => 5
  end.
Definition vpay (v: val) : Z :=
  match v with
  | Vundef => 0
  | Vint n => Int.unsigned n
  | Vlong n => Int64.unsigned n
  | Vfloat f => Int64.unsigned (Float.to_bits f)
  | Vsingle f => Int.unsigned (Float32.to_bits f)
  | Vptr b ofs => Zpos b * 4294967296 + Ptrofs.unsigned ofs
  end.
Definition vcode (v: val) : Z := vtag v * 340282366920938463463374607431768211456 + vpay v.
Definition ovcode (ov: option val) : Z := match ov with None => -1 | Some v => vcode v end.
Definition obcode (ob: option bool) : Z :=
  match ob with None => -1 | Some true => 1 | Some false => 0 end.
Definition bcode (b: bool) : Z := if b then 1 else 0.
(* has_type is a Prop in Coq; use its decision procedure *)
Definition htcode (v: val) (t: typ) : Z := if Val.has_type_dec v t then 1 else 0.
Definition mvcode (mv: memval) : Z :=
  match mv with
  | Undef => 0
  | Byte b => 1 + Byte.unsigned b
  | Fragment _ q n => 300 + 20 * Z.of_nat n + (match q with Q32 => 0 | Q64 => 1 end)
  end.
Definition mvlcode (l: list memval) : Z :=
  fold_right (fun c acc => acc * 1000 + c) 0 (map mvcode l).
Definition vptr_yes (b: block) (o: Z) : bool := true.
Definition vptr_no (b: block) (o: Z) : bool := false.
"""

LEAN_HDR = r"""-- GENERATED by gen_sem_diff.py -- differential test subject
import CCLib
open CC

def vtag : Val → Z
  | .Vundef => 0 | .Vint _ => 1 | .Vlong _ => 2
  | .Vfloat _ => 3 | .Vsingle _ => 4 | .Vptr _ _ => 5
def vpay : Val → Z
  | .Vundef => 0
  | .Vint n => Integers.Int.unsigned n
  | .Vlong n => Integers.Int64.unsigned n
  | .Vfloat f => Integers.Int64.unsigned (Floats.Float.toBits f)
  | .Vsingle f => Integers.Int.unsigned (Floats.Float32.toBits f)
  | .Vptr b ofs => (b.toNat : Z) * 4294967296 + Integers.Ptrofs.unsigned ofs
def vcode (v : Val) : Z := vtag v * 340282366920938463463374607431768211456 + vpay v
def ovcode : Option Val → Z | none => -1 | some v => vcode v
def obcode : Option Bool → Z | none => -1 | some true => 1 | some false => 0
def bcode (b : Bool) : Z := if b then 1 else 0
def mvcode : MemVal → Z
  | .Undef => 0
  | .Byte b => 1 + Integers.Byte.unsigned b
  | .Fragment _ q n => 300 + 20 * (n : Z) + (match q with | .Q32 => 0 | .Q64 => 1)
def mvlcode (l : List MemVal) : Z := (l.map mvcode).foldr (fun c acc => acc * 1000 + c) 0
def vptr_yes : Block → Z → Bool := fun _ _ => true
def vptr_no : Block → Z → Bool := fun _ _ => false
"""

# ---------------------------------------------------------------- test values
def z(v):
    return f"({v})" if v < 0 else str(v)

INTS = [0, 1, -1, 7, -7, 255, 65535, 2147483647, -2147483648, 1000000007]
LONGS = [0, 1, -1, 42, -42, 9223372036854775807, -9223372036854775808, 4294967296]
# double bit patterns: 0.0, 1.0, 2.0, -1.5, 0.1, +inf, NaN
DBITS = [0, 4607182418800017408, 4611686018427387904, 13831004815617130496,
         4591870180066957722, 9218868437227405312, 9221120237041090560]
# single bit patterns: 0.0, 1.0, 2.0, -1.5, 0.1
SBITS = [0, 1065353216, 1073741824, 3217031168, 1036831949]

def vals(coq):
    """The shared pool of test values, rendered for either language."""
    out = []
    out.append(("Vundef", "Val.Vundef"))
    for k in INTS:
        out.append((f"(Vint (Int.repr {z(k)}))",
                    f"(Val.Vint (Integers.Int.repr {z(k)}))"))
    for k in LONGS:
        out.append((f"(Vlong (Int64.repr {z(k)}))",
                    f"(Val.Vlong (Integers.Int64.repr {z(k)}))"))
    for b in DBITS:
        out.append((f"(Vfloat (Float.of_bits (Int64.repr {b})))",
                    f"(Val.Vfloat (Floats.Float.ofBits (Integers.Int64.repr {b})))"))
    for b in SBITS:
        out.append((f"(Vsingle (Float32.of_bits (Int.repr {b})))",
                    f"(Val.Vsingle (Floats.Float32.ofBits (Integers.Int.repr {b})))"))
    for (bl, of) in [(1, 0), (1, 8), (2, 16)]:
        out.append((f"(Vptr {bl}%positive (Ptrofs.repr {of}))",
                    f"(Val.Vptr (Positive.ofNat {bl}) (Integers.Ptrofs.repr {of}))"))
    return [x[0] if coq else x[1] for x in out]

CQV = vals(True)
LNV = vals(False)

ATYPS = ["Tint", "Tfloat", "Tlong", "Tsingle", "Tany32", "Tany64"]
CHUNKS = ["Mbool", "Mint8signed", "Mint8unsigned", "Mint16signed", "Mint16unsigned",
          "Mint32", "Mint64", "Mfloat32", "Mfloat64", "Many32", "Many64"]
CMPS = ["Ceq", "Cne", "Clt", "Cle", "Cgt", "Cge"]

# (coq name, lean name) for ops returning val
UN_V = [("neg", "neg"), ("notint", "notint"), ("notbool", "notbool"),
        ("boolval", "boolval"), ("negl", "negl"), ("notl", "notl"),
        ("negf", "negf"), ("absf", "absf"), ("negfs", "negfs"), ("absfs", "absfs"),
        ("singleoffloat", "singleoffloat"), ("floatofsingle", "floatofsingle"),
        ("longofint", "longofint"), ("longofintu", "longofintu"),
        ("loword", "loword"), ("hiword", "hiword")]
UN_OV = [("intoffloat", "intoffloat"), ("intuoffloat", "intuoffloat"),
         ("longoffloat", "longoffloat"), ("longuoffloat", "longuoffloat"),
         ("floatofint", "floatofint"), ("floatofintu", "floatofintu"),
         ("floatoflong", "floatoflong"), ("floatoflongu", "floatoflongu")]
BIN_V = [("add", "add"), ("sub", "sub"), ("mul", "mul"), ("and", "and"),
         ("or", "or"), ("xor", "xor"), ("shl", "shl"), ("shr", "shr"),
         ("shru", "shru"), ("addl", "addl"), ("subl", "subl"), ("mull", "mull"),
         ("andl", "andl"), ("orl", "orl"), ("xorl", "xorl"),
         ("shll", "shll"), ("shrl", "shrl"), ("shrlu", "shrlu"),
         ("longofwords", "longofwords"),
         ("addf", "addf"), ("subf", "subf"), ("mulf", "mulf"), ("divf", "divf"),
         ("addfs", "addfs"), ("subfs", "subfs"), ("mulfs", "mulfs"), ("divfs", "divfs")]
BIN_OV = [("divs", "divs"), ("mods", "mods"), ("divu", "divu"), ("modu", "modu"),
          ("divls", "divls"), ("modls", "modls"), ("divlu", "divlu"), ("modlu", "modlu")]

coq, lean = [], []
def emit(c, l):
    coq.append(c); lean.append(l)

# ---- Values: unary
for (cq, ln) in UN_V:
    for i in range(len(CQV)):
        emit(f"Compute vcode (Val.{cq} {CQV[i]}).", f"#eval vcode (Val.{ln} {LNV[i]})")
for (cq, ln) in UN_OV:
    for i in range(len(CQV)):
        emit(f"Compute ovcode (Val.{cq} {CQV[i]}).", f"#eval ovcode (Val.{ln} {LNV[i]})")

# ---- Values: binary (all pairs is 43^2 = 1849 per op; keep every 3rd to stay sane)
PAIRS = [(i, j) for i in range(len(CQV)) for j in range(len(CQV))]
PAIRS = PAIRS[::2]
for (cq, ln) in BIN_V:
    for (i, j) in PAIRS:
        emit(f"Compute vcode (Val.{cq} {CQV[i]} {CQV[j]}).",
             f"#eval vcode (Val.{ln} {LNV[i]} {LNV[j]})")
for (cq, ln) in BIN_OV:
    for (i, j) in PAIRS:
        emit(f"Compute ovcode (Val.{cq} {CQV[i]} {CQV[j]}).",
             f"#eval ovcode (Val.{ln} {LNV[i]} {LNV[j]})")

# ---- Values: typing / normalize / load_result / offset_ptr
for t in ATYPS:
    for i in range(len(CQV)):
        emit(f"Compute htcode {CQV[i]} AST.{t}.",
             f"#eval bcode (Val.hasType {LNV[i]} ATyp.{t})")
        emit(f"Compute vcode (Val.normalize {CQV[i]} AST.{t}).",
             f"#eval vcode (Val.normalize {LNV[i]} ATyp.{t})")
for c in CHUNKS:
    for i in range(len(CQV)):
        emit(f"Compute vcode (Val.load_result {c} {CQV[i]}).",
             f"#eval vcode (Val.loadResult Chunk.{c} {LNV[i]})")
for d in [0, 1, 8, -8, 4096]:
    for i in range(len(CQV)):
        emit(f"Compute vcode (Val.offset_ptr {CQV[i]} (Ptrofs.repr {z(d)})).",
             f"#eval vcode (Val.offsetPtr {LNV[i]} (Integers.Ptrofs.repr {z(d)}))")

# ---- Values: comparisons
for c in CMPS:
    for (i, j) in PAIRS[::2]:
        emit(f"Compute obcode (Val.cmp_bool {c} {CQV[i]} {CQV[j]}).",
             f"#eval obcode (Val.cmp_bool Comparison.{c} {LNV[i]} {LNV[j]})")
        emit(f"Compute obcode (Val.cmpl_bool {c} {CQV[i]} {CQV[j]}).",
             f"#eval obcode (Val.cmpl_bool Comparison.{c} {LNV[i]} {LNV[j]})")
        emit(f"Compute obcode (Val.cmpf_bool {c} {CQV[i]} {CQV[j]}).",
             f"#eval obcode (Val.cmpf_bool Comparison.{c} {LNV[i]} {LNV[j]})")
        emit(f"Compute obcode (Val.cmpfs_bool {c} {CQV[i]} {CQV[j]}).",
             f"#eval obcode (Val.cmpfs_bool Comparison.{c} {LNV[i]} {LNV[j]})")
        for (vp_c, vp_l) in [("vptr_yes", "vptr_yes"), ("vptr_no", "vptr_no")]:
            emit(f"Compute obcode (Val.cmpu_bool {vp_c} {c} {CQV[i]} {CQV[j]}).",
                 f"#eval obcode (Val.cmpu_bool {vp_l} Comparison.{c} {LNV[i]} {LNV[j]})")
            emit(f"Compute obcode (Val.cmplu_bool {vp_c} {c} {CQV[i]} {CQV[j]}).",
                 f"#eval obcode (Val.cmplu_bool {vp_l} Comparison.{c} {LNV[i]} {LNV[j]})")

# ---- Memdata: encode / decode
for c in CHUNKS:
    for i in range(len(CQV)):
        emit(f"Compute mvlcode (encode_val {c} {CQV[i]}).",
             f"#eval mvlcode (encodeVal Chunk.{c} {LNV[i]})")
        emit(f"Compute vcode (decode_val {c} (encode_val {c} {CQV[i]})).",
             f"#eval vcode (decodeVal Chunk.{c} (encodeVal Chunk.{c} {LNV[i]}))")
# cross-chunk: store with one chunk, read with another
for c1 in CHUNKS:
    for c2 in CHUNKS:
        for i in range(0, len(CQV), 4):
            emit(f"Compute vcode (decode_val {c2} (encode_val {c1} {CQV[i]})).",
                 f"#eval vcode (decodeVal Chunk.{c2} (encodeVal Chunk.{c1} {LNV[i]}))")
# chunk metadata
for c in CHUNKS:
    emit(f"Compute size_chunk {c}.", f"#eval sizeChunk Chunk.{c}")
    emit(f"Compute align_chunk {c}.", f"#eval alignChunk Chunk.{c}")

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "sem_diff.v"), "w") as f:
    f.write(COQ_HDR + "\n" + "\n".join(coq) + "\n")
with open(os.path.join(here, "SemDiff.lean"), "w") as f:
    f.write(LEAN_HDR + "\n" + "\n".join(lean) + "\n")

print(f"{len(coq)} test cases")
print(f"coq header lines: {len(COQ_HDR.splitlines()) + 1}")
print(f"lean header lines: {len(LEAN_HDR.splitlines()) + 1}")
