#!/usr/bin/env python3
"""Generate matched Rocq and Lean test batteries for CC.Ctypes and CC.Cop.

Level 4 of the differential suite (see diff_all.sh).  Unlike the memory model,
both of these ARE evaluable by Coq's `Compute`: Ctypes is pure arithmetic, and
Cop touches memory only through `Mem.valid_pointer`/`weak_valid_pointer`, which
reduce fine (`perm_dec` is `Defined` and non-recursive).

  - ty_diff.v    evaluates CompCert's real cfrontend/Ctypes.v + cfrontend/Cop.v
  - TyDiff.lean  evaluates CCLib/Ctypes.lean + CCLib/Cop.lean
"""
import os

COQ_HDR = r"""(* GENERATED by gen_ty_diff.py -- differential test oracle *)
From compcert Require Import Coqlib Maps Errors Integers Floats Values Memdata Memory AST Ctypes Cop.
Require Import ZArith List.
Local Open Scope Z_scope.
Set Printing Width 200.

(* --- encoders (same as gen_sem_diff.py) --- *)
Definition vtag (v: val) : Z :=
  match v with
  | Vundef => 0 | Vint _ => 1 | Vlong _ => 2
  | Vfloat _ => 3 | Vsingle _ => 4 | Vptr _ _ => 5
  end.
Definition vpay (v: val) : Z :=
  match v with
  | Vundef => 0
  | Vint n => Int.unsigned n
  | Vlong n => Int64.unsigned n
  | Vfloat f => Int64.unsigned (Float.to_bits f)
  | Vsingle f => Int.unsigned (Float32.to_bits f)
  | Vptr b ofs => Zpos b * 4294967296 + Ptrofs.unsigned ofs
  end.
Definition vcode (v: val) : Z := vtag v * 340282366920938463463374607431768211456 + vpay v.
Definition ovcode (ov: option val) : Z := match ov with None => -1 | Some v => vcode v end.
Definition obcode (ob: option bool) : Z :=
  match ob with None => -1 | Some true => 1 | Some false => 0 end.
Definition bcode (b: bool) : Z := if b then 1 else 0.
Definition ozcode (oz: option Z) : Z := match oz with None => -1 | Some z => z end.
Definition amcode (m: mode) : Z :=
  match m with
  | By_value Mbool => 1 | By_value Mint8signed => 2 | By_value Mint8unsigned => 3
  | By_value Mint16signed => 4 | By_value Mint16unsigned => 5
  | By_value Mint32 => 6 | By_value Mint64 => 7
  | By_value Mfloat32 => 8 | By_value Mfloat64 => 9
  | By_value Many32 => 10 | By_value Many64 => 11
  | By_reference => 20 | By_copy => 21 | By_nothing => 22
  end.
(* field offsets: ok flag, byte offset, and the bitfield designation *)
Definition bfcode (bf: bitfield) : Z :=
  match bf with
  | Full => 0
  | Bits sz sg pos w =>
      1000000
      + (match sz with I8 => 1 | I16 => 2 | I32 => 3 | IBool => 4 end) * 100000
      + (match sg with Signed => 0 | Unsigned => 1 end) * 10000
      + pos * 100 + w
  end.
Definition focode (r: res (Z * bitfield)) : Z :=
  match r with Error _ => -1 | OK (ofs, bf) => ofs * 10000000 + bfcode bf end.
Definition cecode (r: res composite_env) : Z :=
  match r with Error _ => -1 | OK _ => 1 end.
Definition cosz (r: res composite_env) (id: ident) : Z :=
  match r with
  | Error _ => -1
  | OK ce => match ce!id with Some co => co_sizeof co | None => -2 end
  end.
Definition coal (r: res composite_env) (id: ident) : Z :=
  match r with
  | Error _ => -1
  | OK ce => match ce!id with Some co => co_alignof co | None => -2 end
  end.
Definition cork (r: res composite_env) (id: ident) : Z :=
  match r with
  | Error _ => -1
  | OK ce => match ce!id with Some co => Z.of_nat (co_rank co) | None => -2 end
  end.
Definition fo (r: res composite_env) (id fid: ident) : Z :=
  match r with
  | Error _ => -1
  | OK ce => match ce!id with
             | None => -2
             | Some co => match co_su co with
                          | Struct => focode (field_offset ce fid (co_members co))
                          | Union => focode (union_field_offset ce fid (co_members co))
                          end
             end
  end.
Definition szof (r: res composite_env) (t: type) : Z :=
  match r with Error _ => -1 | OK ce => sizeof ce t end.
Definition alof (r: res composite_env) (t: type) : Z :=
  match r with Error _ => -1 | OK ce => alignof ce t end.
Definition cmpl (r: res composite_env) (t: type) : Z :=
  match r with Error _ => -1 | OK ce => bcode (complete_type ce t) end.
Definition rkof (r: res composite_env) (t: type) : Z :=
  match r with Error _ => -1 | OK ce => Z.of_nat (rank_type ce t) end.
Definition cenvOf (r: res composite_env) : composite_env :=
  match r with Error _ => PTree.empty _ | OK ce => ce end.

(* --- the composite environment under test --- *)
Definition _x := 1%positive.
Definition _y := 2%positive.
Definition _z := 3%positive.
Definition _a := 4%positive.
Definition _b := 5%positive.
Definition _c := 6%positive.
Definition _s := 7%positive.
Definition _u := 8%positive.
Definition _bf := 9%positive.
Definition composites : list composite_definition :=
  (Composite _s Struct
     (Member_plain _x (Tint I32 Signed noattr)
      :: Member_plain _y (Tfloat F64 noattr)
      :: Member_plain _z (Tint I8 Signed noattr) :: nil) noattr)
  :: (Composite _u Union
        (Member_plain _x (Tint I32 Signed noattr)
         :: Member_plain _y (Tfloat F64 noattr) :: nil) noattr)
  :: (Composite _bf Struct
        (Member_bitfield _a I32 Signed noattr 3 false
         :: Member_bitfield _b I32 Signed noattr 5 false
         :: Member_plain _c (Tint I32 Signed noattr) :: nil) noattr)
  :: nil.
Definition CE := build_composite_env composites.
Definition ce := cenvOf CE.

(* --- a memory with one valid block (block 1, bytes 0..15) --- *)
Definition m1 := fst (Mem.alloc Mem.empty 0 16).
"""

LEAN_HDR = r"""-- GENERATED by gen_ty_diff.py -- differential test subject
import CCLib
open CC

def vtag : Val → Z
  | .Vundef => 0 | .Vint _ => 1 | .Vlong _ => 2
  | .Vfloat _ => 3 | .Vsingle _ => 4 | .Vptr _ _ => 5
def vpay : Val → Z
  | .Vundef => 0
  | .Vint n => Integers.Int.unsigned n
  | .Vlong n => Integers.Int64.unsigned n
  | .Vfloat f => Integers.Int64.unsigned (Floats.Float.toBits f)
  | .Vsingle f => Integers.Int.unsigned (Floats.Float32.toBits f)
  | .Vptr b ofs => (b.toNat : Z) * 4294967296 + Integers.Ptrofs.unsigned ofs
def vcode (v : Val) : Z := vtag v * 340282366920938463463374607431768211456 + vpay v
def ovcode : Option Val → Z | none => -1 | some v => vcode v
def obcode : Option Bool → Z | none => -1 | some true => 1 | some false => 0
def bcode (b : Bool) : Z := if b then 1 else 0
def ozcode : Option Z → Z | none => -1 | some z => z
def amcode : AccessMode → Z
  | .By_value .Mbool => 1 | .By_value .Mint8signed => 2 | .By_value .Mint8unsigned => 3
  | .By_value .Mint16signed => 4 | .By_value .Mint16unsigned => 5
  | .By_value .Mint32 => 6 | .By_value .Mint64 => 7
  | .By_value .Mfloat32 => 8 | .By_value .Mfloat64 => 9
  | .By_value .Many32 => 10 | .By_value .Many64 => 11
  | .By_reference => 20 | .By_copy => 21 | .By_nothing => 22
def bfcode : Bitfield → Z
  | .Full => 0
  | .Bits sz sg pos w =>
      1000000
      + (match sz with | .I8 => 1 | .I16 => 2 | .I32 => 3 | .IBool => 4) * 100000
      + (match sg with | .Signed => 0 | .Unsigned => 1) * 10000
      + pos * 100 + w
def focode : Res (Z × Bitfield) → Z
  | .Error _ => -1
  | .OK (ofs, bf) => ofs * 10000000 + bfcode bf
def cecode : Res CompositeEnv → Z | .Error _ => -1 | .OK _ => 1
def cenvOf : Res CompositeEnv → CompositeEnv
  | .Error _ => PTree.empty
  | .OK ce => ce

def _x : Ident := Positive.ofNat 1
def _y : Ident := Positive.ofNat 2
def _z : Ident := Positive.ofNat 3
def _a : Ident := Positive.ofNat 4
def _b : Ident := Positive.ofNat 5
def _c : Ident := Positive.ofNat 6
def _s : Ident := Positive.ofNat 7
def _u : Ident := Positive.ofNat 8
def _bf : Ident := Positive.ofNat 9
def composites : List CompositeDef :=
  [ .Composite _s .Struct
      [ .Member_plain _x (Ty.Tint .I32 .Signed noattr),
        .Member_plain _y (Ty.Tfloat .F64 noattr),
        .Member_plain _z (Ty.Tint .I8 .Signed noattr) ] noattr,
    .Composite _u .Union
      [ .Member_plain _x (Ty.Tint .I32 .Signed noattr),
        .Member_plain _y (Ty.Tfloat .F64 noattr) ] noattr,
    .Composite _bf .Struct
      [ .Member_bitfield _a .I32 .Signed noattr 3 false,
        .Member_bitfield _b .I32 .Signed noattr 5 false,
        .Member_plain _c (Ty.Tint .I32 .Signed noattr) ] noattr ]
def CE : Res CompositeEnv := buildCompositeEnv composites
def ce : CompositeEnv := cenvOf CE

def cosz (r : Res CompositeEnv) (id : Ident) : Z :=
  match r with
  | .Error _ => -1
  | .OK ce => match ce.get id with | some co => co.co_sizeof | none => -2
def coal (r : Res CompositeEnv) (id : Ident) : Z :=
  match r with
  | .Error _ => -1
  | .OK ce => match ce.get id with | some co => co.co_alignof | none => -2
def cork (r : Res CompositeEnv) (id : Ident) : Z :=
  match r with
  | .Error _ => -1
  | .OK ce => match ce.get id with | some co => (co.co_rank : Z) | none => -2
def fo (r : Res CompositeEnv) (id fid : Ident) : Z :=
  match r with
  | .Error _ => -1
  | .OK ce => match ce.get id with
              | none => -2
              | some co => match co.co_su with
                           | .Struct => focode (fieldOffset ce fid co.co_members)
                           | .Union => focode (unionFieldOffset ce fid co.co_members)
def szof (r : Res CompositeEnv) (t : Ty) : Z :=
  match r with | .Error _ => -1 | .OK ce => sizeof ce t
def alof (r : Res CompositeEnv) (t : Ty) : Z :=
  match r with | .Error _ => -1 | .OK ce => alignof ce t
def cmplT (r : Res CompositeEnv) (t : Ty) : Z :=
  match r with | .Error _ => -1 | .OK ce => bcode (completeType ce t)
def rkof (r : Res CompositeEnv) (t : Ty) : Z :=
  match r with | .Error _ => -1 | .OK ce => (rankType ce t : Z)

def m1 : Mem := (Mem.alloc Mem.empty 0 16).1
"""

# (coq, lean) renderings of the types under test
TYPES = [
    ("Tvoid", "Ty.Tvoid"),
    ("(Tint I8 Signed noattr)", "(Ty.Tint .I8 .Signed noattr)"),
    ("(Tint I8 Unsigned noattr)", "(Ty.Tint .I8 .Unsigned noattr)"),
    ("(Tint I16 Signed noattr)", "(Ty.Tint .I16 .Signed noattr)"),
    ("(Tint I16 Unsigned noattr)", "(Ty.Tint .I16 .Unsigned noattr)"),
    ("(Tint I32 Signed noattr)", "(Ty.Tint .I32 .Signed noattr)"),
    ("(Tint I32 Unsigned noattr)", "(Ty.Tint .I32 .Unsigned noattr)"),
    ("(Tint IBool Unsigned noattr)", "(Ty.Tint .IBool .Unsigned noattr)"),
    ("(Tlong Signed noattr)", "(Ty.Tlong .Signed noattr)"),
    ("(Tlong Unsigned noattr)", "(Ty.Tlong .Unsigned noattr)"),
    ("(Tfloat F32 noattr)", "(Ty.Tfloat .F32 noattr)"),
    ("(Tfloat F64 noattr)", "(Ty.Tfloat .F64 noattr)"),
    ("(Tpointer (Tint I32 Signed noattr) noattr)",
     "(Ty.Tpointer (Ty.Tint .I32 .Signed noattr) noattr)"),
    ("(Tarray (Tint I32 Signed noattr) 3 noattr)",
     "(Ty.Tarray (Ty.Tint .I32 .Signed noattr) 3 noattr)"),
    ("(Tarray (Tint I8 Signed noattr) 7 noattr)",
     "(Ty.Tarray (Ty.Tint .I8 .Signed noattr) 7 noattr)"),
    ("(Tarray (Tstruct _s noattr) 2 noattr)",
     "(Ty.Tarray (Ty.Tstruct _s noattr) 2 noattr)"),
    ("(Tfunction (Tint I32 Signed noattr :: nil) (Tint I32 Signed noattr) cc_default)",
     "(Ty.Tfunction [Ty.Tint .I32 .Signed noattr] (Ty.Tint .I32 .Signed noattr) cc_default)"),
    ("(Tstruct _s noattr)", "(Ty.Tstruct _s noattr)"),
    ("(Tunion _u noattr)", "(Ty.Tunion _u noattr)"),
    ("(Tstruct _bf noattr)", "(Ty.Tstruct _bf noattr)"),
    # alignment attributes
    ("(Tint I8 Signed {| attr_volatile := false; attr_alignas := Some 4%N |})",
     "(Ty.Tint .I8 .Signed { attr_volatile := false, attr_alignas := some 4 })"),
    ("(Tint I32 Signed {| attr_volatile := true; attr_alignas := None |})",
     "(Ty.Tint .I32 .Signed { attr_volatile := true, attr_alignas := none })"),
]

VALS = [
    ("Vundef", "Val.Vundef"),
    ("(Vint (Int.repr 0))", "(Val.Vint (Integers.Int.repr 0))"),
    ("(Vint (Int.repr 1))", "(Val.Vint (Integers.Int.repr 1))"),
    ("(Vint (Int.repr (-1)))", "(Val.Vint (Integers.Int.repr (-1)))"),
    ("(Vint (Int.repr 255))", "(Val.Vint (Integers.Int.repr 255))"),
    ("(Vint (Int.repr 65535))", "(Val.Vint (Integers.Int.repr 65535))"),
    ("(Vint (Int.repr 1000000007))", "(Val.Vint (Integers.Int.repr 1000000007))"),
    ("(Vlong (Int64.repr 0))", "(Val.Vlong (Integers.Int64.repr 0))"),
    ("(Vlong (Int64.repr 42))", "(Val.Vlong (Integers.Int64.repr 42))"),
    ("(Vlong (Int64.repr (-42)))", "(Val.Vlong (Integers.Int64.repr (-42)))"),
    ("(Vfloat (Float.of_bits (Int64.repr 4611686018427387904)))",
     "(Val.Vfloat (Floats.Float.ofBits (Integers.Int64.repr 4611686018427387904)))"),
    ("(Vfloat (Float.of_bits (Int64.repr 4591870180066957722)))",
     "(Val.Vfloat (Floats.Float.ofBits (Integers.Int64.repr 4591870180066957722)))"),
    ("(Vsingle (Float32.of_bits (Int.repr 1065353216)))",
     "(Val.Vsingle (Floats.Float32.ofBits (Integers.Int.repr 1065353216)))"),
    ("(Vptr 1%positive (Ptrofs.repr 0))",
     "(Val.Vptr (Positive.ofNat 1) (Integers.Ptrofs.repr 0))"),
    ("(Vptr 1%positive (Ptrofs.repr 8))",
     "(Val.Vptr (Positive.ofNat 1) (Integers.Ptrofs.repr 8))"),
    ("(Vptr 2%positive (Ptrofs.repr 0))",
     "(Val.Vptr (Positive.ofNat 2) (Integers.Ptrofs.repr 0))"),
]

UNOPS = [("Onotbool", "Unop.Onotbool"), ("Onotint", "Unop.Onotint"),
         ("Oneg", "Unop.Oneg"), ("Oabsfloat", "Unop.Oabsfloat")]
BINOPS = [("Oadd", "Binop.Oadd"), ("Osub", "Binop.Osub"), ("Omul", "Binop.Omul"),
          ("Odiv", "Binop.Odiv"), ("Omod", "Binop.Omod"), ("Oand", "Binop.Oand"),
          ("Oor", "Binop.Oor"), ("Oxor", "Binop.Oxor"), ("Oshl", "Binop.Oshl"),
          ("Oshr", "Binop.Oshr"), ("Oeq", "Binop.Oeq"), ("One", "Binop.One"),
          ("Olt", "Binop.Olt"), ("Ogt", "Binop.Ogt"), ("Ole", "Binop.Ole"),
          ("Oge", "Binop.Oge")]
FIELDS = [("_x", "_x"), ("_y", "_y"), ("_z", "_z"),
          ("_a", "_a"), ("_b", "_b"), ("_c", "_c")]

coq, lean = [], []
def emit(c, l):
    coq.append(c); lean.append(l)

# ---------------------------------------------------------------- Ctypes
emit("Compute cecode CE.", "#eval cecode CE")
for (cid, lid) in [("_s", "_s"), ("_u", "_u"), ("_bf", "_bf")]:
    emit(f"Compute cosz CE {cid}.", f"#eval cosz CE {lid}")
    emit(f"Compute coal CE {cid}.", f"#eval coal CE {lid}")
    emit(f"Compute cork CE {cid}.", f"#eval cork CE {lid}")
    for (cf, lf) in FIELDS:
        emit(f"Compute fo CE {cid} {cf}.", f"#eval fo CE {lid} {lf}")
for (ct, lt) in TYPES:
    emit(f"Compute szof CE {ct}.", f"#eval szof CE {lt}")
    emit(f"Compute alof CE {ct}.", f"#eval alof CE {lt}")
    emit(f"Compute cmpl CE {ct}.", f"#eval cmplT CE {lt}")
    emit(f"Compute rkof CE {ct}.", f"#eval rkof CE {lt}")
    emit(f"Compute amcode (access_mode {ct}).", f"#eval amcode (accessMode {lt})")
    emit(f"Compute bcode (type_is_volatile {ct}).",
         f"#eval bcode (typeIsVolatile {lt})")
    # typeconv is observed through the size/alignment of its result
    emit(f"Compute szof CE (typeconv {ct}).", f"#eval szof CE (typeconv {lt})")

# ---------------------------------------------------------------- Cop
# sem_cast over all (value, from-type, to-type) with a modest type subset
CTY = TYPES[:14]
for (cv, lv) in VALS:
    for (ct1, lt1) in CTY:
        for (ct2, lt2) in CTY:
            emit(f"Compute ovcode (sem_cast {cv} {ct1} {ct2} m1).",
                 f"#eval ovcode (Cop.semCast {lv} {lt1} {lt2} m1)")
# bool_val
for (cv, lv) in VALS:
    for (ct, lt) in TYPES:
        emit(f"Compute obcode (bool_val {cv} {ct} m1).",
             f"#eval obcode (Cop.boolVal {lv} {lt} m1)")
# unary operations
for (co, lo) in UNOPS:
    for (cv, lv) in VALS:
        for (ct, lt) in CTY:
            emit(f"Compute ovcode (sem_unary_operation {co} {cv} {ct} m1).",
                 f"#eval ovcode (Cop.semUnaryOperation {lo} {lv} {lt} m1)")
# binary operations (subset of value/type pairs to keep the file manageable)
BV = VALS[1:]
BT = TYPES[5:12] + [TYPES[12]]
for (co, lo) in BINOPS:
    for i in range(len(BV)):
        for j in range(len(BV)):
            if (i + j) % 2 != 0:
                continue
            ct1, lt1 = BT[i % len(BT)]
            ct2, lt2 = BT[j % len(BT)]
            cv1, lv1 = BV[i]
            cv2, lv2 = BV[j]
            emit(f"Compute ovcode (sem_binary_operation ce {co} {cv1} {ct1} {cv2} {ct2} m1).",
                 f"#eval ovcode (Cop.semBinaryOperation ce {lo} {lv1} {lt1} {lv2} {lt2} m1)")
# pointer arithmetic explicitly (scaling by sizeof)
for (ct, lt) in [("(Tint I32 Signed noattr)", "(Ty.Tint .I32 .Signed noattr)"),
                 ("(Tstruct _s noattr)", "(Ty.Tstruct _s noattr)"),
                 ("(Tint I8 Signed noattr)", "(Ty.Tint .I8 .Signed noattr)")]:
    for k in [0, 1, 3, -1]:
        kk = f"({k})" if k < 0 else str(k)
        emit(f"Compute ovcode (sem_add ce (Vptr 1%positive (Ptrofs.repr 0)) (Tpointer {ct} noattr) (Vint (Int.repr {kk})) (Tint I32 Signed noattr) m1).",
             f"#eval ovcode (Cop.semAdd ce (Val.Vptr (Positive.ofNat 1) (Integers.Ptrofs.repr 0)) (Ty.Tpointer {lt} noattr) (Val.Vint (Integers.Int.repr {kk})) (Ty.Tint .I32 .Signed noattr) m1)")
        emit(f"Compute ovcode (sem_sub ce (Vptr 1%positive (Ptrofs.repr 16)) (Tpointer {ct} noattr) (Vint (Int.repr {kk})) (Tint I32 Signed noattr) m1).",
             f"#eval ovcode (Cop.semSub ce (Val.Vptr (Positive.ofNat 1) (Integers.Ptrofs.repr 16)) (Ty.Tpointer {lt} noattr) (Val.Vint (Integers.Int.repr {kk})) (Ty.Tint .I32 .Signed noattr) m1)")
    # pointer difference
    emit(f"Compute ovcode (sem_sub ce (Vptr 1%positive (Ptrofs.repr 16)) (Tpointer {ct} noattr) (Vptr 1%positive (Ptrofs.repr 0)) (Tpointer {ct} noattr) m1).",
         f"#eval ovcode (Cop.semSub ce (Val.Vptr (Positive.ofNat 1) (Integers.Ptrofs.repr 16)) (Ty.Tpointer {lt} noattr) (Val.Vptr (Positive.ofNat 1) (Integers.Ptrofs.repr 0)) (Ty.Tpointer {lt} noattr) m1)")
# switch arguments
for (cv, lv) in VALS:
    for (ct, lt) in CTY:
        emit(f"Compute ozcode (sem_switch_arg {cv} {ct}).",
             f"#eval ozcode (Cop.semSwitchArg {lv} {lt})")

# ---------------------------------------------------------------- Phase 3 additions
# alignof_blockcopy (used by Clight's By_copy assignment)
for (ct, lt) in TYPES:
    emit(f"Compute (match CE with Error _ => -1 | OK ce => alignof_blockcopy ce {ct} end).",
         f"#eval (match CE with | .Error _ => -1 | .OK ce => alignofBlockcopy ce {lt})")

# Cop's bitfield helpers: carrier chunk (observed via its size and alignment),
# bit position, extraction and normalization
BFSZ = [("I8", ".I8"), ("I16", ".I16"), ("I32", ".I32"), ("IBool", ".IBool")]
BFSG = [("Signed", ".Signed"), ("Unsigned", ".Unsigned")]
for (csz, lsz) in BFSZ:
    emit(f"Compute size_chunk (chunk_for_carrier {csz}).",
         f"#eval sizeChunk (Cop.chunkForCarrier {lsz})")
    emit(f"Compute align_chunk (chunk_for_carrier {csz}).",
         f"#eval alignChunk (Cop.chunkForCarrier {lsz})")
    emit(f"Compute bitsize_carrier {csz}.", f"#eval Cop.bitsizeCarrier {lsz}")
    for pos in [0, 1, 3, 7]:
        for width in [1, 3, 5, 8]:
            emit(f"Compute first_bit {csz} {pos} {width}.",
                 f"#eval Cop.firstBit {lsz} {pos} {width}")
            for (csg, lsg) in BFSG:
                for v in [0, 1, 255, 65535, 1000000007]:
                    emit(f"Compute Int.signed (bitfield_extract {csz} {csg} {pos} {width} (Int.repr {v})).",
                         f"#eval Integers.Int.signed (Cop.bitfieldExtract {lsz} {lsg} {pos} {width} (Integers.Int.repr {v}))")
                    emit(f"Compute Int.signed (bitfield_normalize {csz} {csg} {width} (Int.repr {v})).",
                         f"#eval Integers.Int.signed (Cop.bitfieldNormalize {lsz} {lsg} {width} (Integers.Int.repr {v}))")

# the underlying Integers bitfield primitives
for pos in [0, 1, 5, 16, 31]:
    for width in [1, 4, 8, 16]:
        for v in [0, 1, 255, 4294967295, 1000000007]:
            emit(f"Compute Int.unsigned (Int.unsigned_bitfield_extract {pos} {width} (Int.repr {v})).",
                 f"#eval Integers.Int.unsigned (Integers.Int.unsigned_bitfield_extract {pos} {width} (Integers.Int.repr {v}))")
            emit(f"Compute Int.signed (Int.signed_bitfield_extract {pos} {width} (Int.repr {v})).",
                 f"#eval Integers.Int.signed (Integers.Int.signed_bitfield_extract {pos} {width} (Integers.Int.repr {v}))")
            for p2 in [0, 7, 255]:
                emit(f"Compute Int.unsigned (Int.bitfield_insert {pos} {width} (Int.repr {v}) (Int.repr {p2})).",
                     f"#eval Integers.Int.unsigned (Integers.Int.bitfield_insert {pos} {width} (Integers.Int.repr {v}) (Integers.Int.repr {p2}))")

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "ty_diff.v"), "w") as f:
    f.write(COQ_HDR + "\n" + "\n".join(coq) + "\n")
with open(os.path.join(here, "TyDiff.lean"), "w") as f:
    f.write(LEAN_HDR + "\n" + "\n".join(lean) + "\n")

print(f"{len(coq)} test cases")
