#!/usr/bin/env python3
"""Generate random, UB-free C programs for the whole-program differential test.

A Csmith-in-miniature.  The programs are deliberately constructed so that they
have NO undefined behaviour, because the comparison against `ccomp -interp` is
only meaningful for well-defined programs:

  * all arithmetic is on `unsigned`, where wraparound is defined (signed overflow
    would be UB);
  * divisors and moduli are forced nonzero with `| 1u`;
  * shift amounts are masked with `& 31`;
  * every variable is initialized before use;
  * loops have constant trip counts, so every program terminates;
  * `main` returns a value masked into `[0, 2^31)` so the result is a plain int.

Usage: gen_random_c.py <outdir> <count> [seed]
"""
import os, random, sys

BIN = ['+', '-', '*', '&', '|', '^']
CMP = ['<', '>', '<=', '>=', '==', '!=']

class Gen:
    def __init__(self, rng, nvars):
        self.rng = rng
        self.vars = [f'v{i}' for i in range(nvars)]

    def expr(self, depth=0):
        r = self.rng
        if depth >= 3 or r.random() < 0.3:
            return r.choice([lambda: str(r.randrange(0, 1 << 16)) + 'u',
                             lambda: r.choice(self.vars)])()
        k = r.random()
        if k < 0.50:
            return f'({self.expr(depth+1)} {r.choice(BIN)} {self.expr(depth+1)})'
        if k < 0.62:
            return f'({self.expr(depth+1)} / (({self.expr(depth+1)}) | 1u))'
        if k < 0.74:
            return f'({self.expr(depth+1)} % (({self.expr(depth+1)}) | 1u))'
        if k < 0.86:
            op = r.choice(['<<', '>>'])
            return f'({self.expr(depth+1)} {op} (({self.expr(depth+1)}) & 31u))'
        return f'((unsigned)({self.expr(depth+1)} {r.choice(CMP)} {self.expr(depth+1)}))'

    def stmt(self, depth, indent):
        r = self.rng
        pad = '  ' * indent
        if depth >= 2 or r.random() < 0.45:
            return f'{pad}{r.choice(self.vars)} = {self.expr()};\n'
        k = r.random()
        if k < 0.35:
            body = ''.join(self.stmt(depth+1, indent+1) for _ in range(r.randint(1, 3)))
            els = ''
            if r.random() < 0.5:
                els = (f'{pad}}} else {{\n'
                       + ''.join(self.stmt(depth+1, indent+1) for _ in range(r.randint(1, 2))))
            return (f'{pad}if ({self.expr()} {r.choice(CMP)} {self.expr()}) {{\n'
                    + body + els + f'{pad}}}\n')
        if k < 0.70:
            n = r.randint(1, 6)
            iv = f'i{depth}'
            body = ''.join(self.stmt(depth+1, indent+1) for _ in range(r.randint(1, 3)))
            if r.random() < 0.25:
                body += f'{pad}  if ({r.choice(self.vars)} % 3u == 0u) continue;\n'
            if r.random() < 0.25:
                body += f'{pad}  if ({r.choice(self.vars)} % 7u == 1u) break;\n'
            return (f'{pad}for (unsigned {iv} = 0u; {iv} < {n}u; {iv}++) {{\n'
                    + body + f'{pad}}}\n')
        # switch
        v = r.choice(self.vars)
        arms = ''
        for c in range(r.randint(2, 3)):
            arms += f'{pad}  case {c}u:\n'
            arms += ''.join(self.stmt(depth+1, indent+2) for _ in range(r.randint(1, 2)))
            if r.random() < 0.75:
                arms += f'{pad}    break;\n'
        arms += f'{pad}  default:\n'
        arms += ''.join(self.stmt(depth+1, indent+2) for _ in range(1))
        return f'{pad}switch ({v} % 4u) {{\n' + arms + f'{pad}}}\n'

def program(seed):
    r = random.Random(seed)
    g = Gen(r, r.randint(3, 5))
    lines = ['/* generated by gen_random_c.py, seed %d -- UB-free by construction */' % seed]
    # a helper function, called from main
    h = Gen(r, 2)
    lines.append('static unsigned helper(unsigned a, unsigned b) {')
    lines.append('  unsigned v0 = a, v1 = b;')
    hg = Gen(r, 2)
    hg.vars = ['v0', 'v1']
    for _ in range(r.randint(1, 4)):
        lines.append(hg.stmt(1, 1).rstrip('\n'))
    lines.append('  return v0 ^ v1;')
    lines.append('}')
    lines.append('int main(void) {')
    for i, v in enumerate(g.vars):
        lines.append(f'  unsigned {v} = {r.randrange(0, 1 << 16)}u;')
    for _ in range(r.randint(3, 8)):
        lines.append(g.stmt(0, 1).rstrip('\n'))
    a, b = r.sample(g.vars, 2)
    lines.append(f'  unsigned acc = helper({a}, {b});')
    for v in g.vars:
        lines.append(f'  acc = acc * 31u + {v};')
    lines.append('  return (int)(acc & 0x7fffffffu);')
    lines.append('}')
    return '\n'.join(lines) + '\n'

def main():
    outdir, count = sys.argv[1], int(sys.argv[2])
    seed0 = int(sys.argv[3]) if len(sys.argv) > 3 else 1
    os.makedirs(outdir, exist_ok=True)
    for k in range(count):
        s = seed0 + k
        with open(os.path.join(outdir, f'r{s:04d}.c'), 'w') as f:
            f.write(program(s))
    print(f'{count} programs in {outdir}')

main()
